version: '3.4'
services:
  passport-db:
    container_name: passport-db
    image: mysql:5.7.14
    environment:
      MYSQL_DATABASE: passport
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--port=3306", "--user=root", "--password=password"]
      timeout: 20s
      retries: 10
    volumes:
      - ./dependancies/passport-mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

  flyway-db-reset:
    container_name: flyway_db_reset
    image: boxfuse/flyway:5.0.2
    command: -url=jdbc:mysql://passport-db -schemas=passport -user=root -password=password clean migrate
    depends_on: ["passport-db"]
    volumes:
      - ./src/main/resources/database_migrations:/flyway/sql
#      - ./cloudsql/src/main/resources/db/config/flyway.config:/flyway/config/flyway.config

  passport-web:
    container_name: passport-web
    build:
      dockerfile: Dockerfile
      context: .
      args:
#        - dir=./target/demo-0.0.1-SNAPSHOT.war
        - port=8080
    ports:
      - 8090:8080
    depends_on: ["passport-db", "flyway-db-reset"]
