spring:
  application:
    name: web-passport-socket  # Service registers under this name
    config:
      enabled: false
  datasource:
    initialization-mode: always
    url: jdbc:mysql://passport-db/passport
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
#  flyway:
#    locations: classpath:database_migrations
#    clean-on-validation-error: true
#    clean-disabled: false
#    clean: true
  management:
    endpoints:
      web:
        exposure:
          include: "*"

security:
  enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    servlet:
      context-path: /_ah

server:
  servlet:
    jsp:
      init-parameters:
        listings: true

logging:
  level:
    root: INFO
    org.flyway: TRACE
    com.zaxxer.hikari.HikariDataSource: TRACE

#datasources:
#  default:
#    url: jdbc:mysql://104.196.220.75/passport
#    username: "root"
#    password: "KlanddunmcjepjsP"
#    maximumPoolSize: 15
#    minimumIdle: 5
#    driverClassName: com.mysql.jdbc.Driver
